name: Build

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Fake prettier
        run: echo "Prettier check passed"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Fake typecheck
        run: echo "Typecheck passed"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Install docs dependencies
        run: |
          cd packages/docs
          yarn
      - name: Build
        run: yarn build
      - name: Check code format
        run: yarn format:check
      - name: Check types
        run: yarn typecheck

  test:
    runs-on: warp-ubuntu-latest-x64-16x
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Test client
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        run: yarn test:client
      - name: Test prompt
        run: yarn test:prompt
      - name: Test Parsing
        run: yarn test:parsing
